spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://${EC2_HOST}:3306/tripletDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: ${MYSQL_USERNAME}
    #    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/newjibs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: takealook
    password: '0205'

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [ client-id ]
            client-secret: [ client-secret ]
            scope:
              - profile
              - email
          naver:
            client-id: [ client-id ]
            client-secret: [ client-secret ]
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: [ client-id ]
            client-secret: [ client-secret ]
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #show-sql: true

  profiles:
    active: jwt

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

