server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  sql:
    init:
      mode: always

  profiles:
    active: jwt, api

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
    com.ssafy.newjibs: DEBUG

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false