jwt:
  secret: "secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey"
  expiration: 86400 # 토큰 만료 시간 (초 단위, 여기서는 24시간)
  token-prefix: Bearer
  header: Authorization

security:
  jwt:
    issuer: your-issuer # 발급자 (issuer) 이름
    audience: your-audience # 토큰 대상 (audience) 이름

